# Generated by Django 5.1.4 on 2025-02-05 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_day_alter_lesson_rate_remove_lesson_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson',
            new_name='StudentCard',
        ),
    ]
