# Generated by Django 5.1.4 on 2025-02-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_lesson_studentcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day',
            new_name='name',
        ),
    ]
