# Generated by Django 5.1.4 on 2025-02-07 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_day_day_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('total_money', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentcard')),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyRecord',
        ),
    ]
