# Generated by Django 5.1.4 on 2025-02-10 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_monthlysummary_tutor_student_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysummary',
            name='student_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summary', to='app.studentcard'),
        ),
    ]
