# Generated by Django 5.1.4 on 2025-02-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_monthlysummary_student_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysummary',
            name='tutor',
        ),
    ]
